on:
  workflow_dispatch:
    inputs: {}
  push:
    tags:
      - '*'

name: Release

jobs:
  release:
    name: Release
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.x.x'

      - name: Download Dalamud
        run: |
          Invoke-WebRequest -Uri https://goatcorp.github.io/dalamud-distrib/stg/latest.zip -OutFile latest.zip
          Expand-Archive -Force latest.zip "$env:AppData\XIVLauncher\addon\Hooks\dev\"

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: |
          $ver = '${{ github.ref }}' -replace 'refs/tags/',''
          dotnet build --no-restore -c Release --nologo -p:Version=$ver

      - name: Write version into manifest
        run: |
          $ver = '${{ github.ref }}' -replace 'refs/tags/',''
          $path = './ArrowNavigation/bin/Release/net8.0-windows/ArrowNavigation.json'
          $content = get-content -path $path
          $content = $content -replace '0.0.0.0',$ver
          set-content -Path $path -Value $content

      - name: Packing Release
        run: |
          pushd ArrowNavigation/bin/Release/net8.0-windows
          7z a ../ArrowNavigation.zip *
          popd
        shell: bash

      - name: Create Release
        uses: ncipollo/release-action@v1.12.0
        with:
          name: ArrowNavigation ${{ github.ref_name }}
          artifacts: "./ArrowNavigation/bin/Release/*.zip"
          tag: ${{ github.ref_name }}
          body: "Map too cumbersome to navigate? Mini map hard to use? Use a floating arrow that points where to go!"
          omitBodyDuringUpdate: true
          allowUpdates: true
          replacesArtifacts: true
          token: ${{ secrets.RELEASE }}

      - name: Write out repo.json
        run: |
          $ver = '${{ github.ref_name }}'
          $path = './repo.json'
          $json = Get-Content -Raw $path | ConvertFrom-Json
          $json[0].AssemblyVersion = $ver
          $json[0].TestingAssemblyVersion = $ver
          $json[0].DownloadLinkInstall = $json.DownloadLinkInstall -replace '[^/]+/ArrowNavigation.zip',"$ver/ArrowNavigation.zip"
          $json[0].DownloadLinkTesting = $json.DownloadLinkTesting -replace '[^/]+/ArrowNavigation.zip',"$ver/ArrowNavigation.zip"
          $json[0].DownloadLinkUpdate = $json.DownloadLinkUpdate -replace '[^/]+/ArrowNavigation.zip',"$ver/ArrowNavigation.zip"
          $content = $json | ConvertTo-Json -AsArray
          set-content -Path $path -Value $content

      - name: Commit repo.json
        run: |
          git config --global user.name "Actions User"
          git config --global user.email "actions@github.com"
          git fetch origin master
          git branch -f master ${{ github.sha }}
          git checkout master
          git add repo.json
          git commit -m "[CI] Updating repo.json for ${{ github.ref_name }}" || true
          git push origin master
